title: Fengyi
email: fengyi.tsai@gmail.com
description: Fengyi Tsai — Software Engineer
baseurl: "/blog"
url: "https://fengyitsai.github.io"
author: "Fengyi Tsai"

theme:
  social:
    github: fengyitsai

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - .gitignore
